// <auto-generated />
using Duybansachdao_Test.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Duybansachdao_Test.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231121084258_seedingCategoryTable")]
    partial class seedingCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Duybansachdao_Test.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "A man recuse the police",
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "A man recuse the police",
                            DisplayOrder = 2,
                            Name = "Romance"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "A man recuse the police",
                            DisplayOrder = 3,
                            Name = "Historical"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "A man recuse the police",
                            DisplayOrder = 4,
                            Name = "Drama"
                        },
                        new
                        {
                            CategoryId = 6,
                            Description = "A man recuse the police",
                            DisplayOrder = 5,
                            Name = "Science"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
